stages:
  download:
    cmd: python3 stages/00_download.py
    deps:
      - stages/01_download.sh
    outs:
      - download
  build: 
    cmd: python3 stages/01_process.py
    deps:
      - stages/01_process.py
      - download
    outs:
      - unzip
      - brick